# Use the specified Red Hat UBI9 Python 3.11 base image
FROM registry.redhat.io/ubi9/python-311@sha256:f41bd5f6e2f36c239f2b25871685de5ff487c49bc9053e8dbbd1e753f2384710

# Set metadata
LABEL name="clementine" \
      version="1.0.0" \
      description="Clementine Slack bot for Tangerine AI integration"

# Set working directory
WORKDIR /app

# Install pipenv and upgrade pip
RUN pip install --upgrade pip pipenv

# Copy dependency files
COPY Pipfile Pipfile.lock ./

# Install dependencies using pipenv
RUN pipenv install --system --deploy

# Copy application code
COPY . .

# Create directory for database storage with proper permissions
RUN mkdir -p /app/data && \
    chown -R default:root /app/data && \
    chmod -R g+w /app/data

# Set default environment variables
# Required variables (must be set at runtime)
ENV SLACK_BOT_TOKEN="" \
    SLACK_SIGNING_SECRET="" \
    SLACK_APP_TOKEN="" \
    TANGERINE_API_URL="" \
    TANGERINE_API_TOKEN=""

# Optional variables with defaults
ENV LOG_LEVEL="INFO" \
    LOG_FORMAT="%(asctime)s - %(name)s - %(levelname)s - %(message)s" \
    LOG_FILE="" \
    BOT_NAME="Clementine" \
    ASSISTANT_LIST="konflux" \
    DEFAULT_PROMPT="You are a helpful assistant." \
    TANGERINE_API_TIMEOUT="500" \
    ROOM_CONFIG_DB_PATH="/app/data/room_configs.db" \
    AI_DISCLOSURE_ENABLED="true" \
    AI_DISCLOSURE_TEXT="This response was generated by AI. Please verify important information." \
    FEEDBACK_ENABLED="true"

# Create volume for persistent database storage
VOLUME ["/app/data"]

# Switch to non-root user for security
USER default

# Health check to ensure the application is running
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
    CMD python -c "import sqlite3; conn = sqlite3.connect('$ROOM_CONFIG_DB_PATH'); conn.close()" || exit 1

# Expose port (though Socket Mode doesn't require it, useful for documentation)
EXPOSE 3000

# Set the entrypoint
ENTRYPOINT ["python", "app.py"]
