name: Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Install dependencies
      run: |
        pipenv install --dev

    - name: Install linting tools
      run: |
        pipenv install --dev flake8

    - name: Basic syntax check with flake8
      run: |
        pipenv run flake8 clementine/ tests/ --max-line-length=120 --extend-ignore=E203,W503,E501 --select=E9,F63,F7,F82 